### PR TITLE
Adding mongo data source type

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Investigation: Add mongodb datasource.

Required to run: 
https://github.com/aerogear/data-sync-server/pull/100

### CODE REVIEW

**Comment by wtrocki** [comment]
See https://github.com/aerogear/data-sync-server/pull/100

**Review by pb82 — APPROVED** [review]
This is a good start. To actually implement the data source configuration you need to add the option here: https://github.com/aerogear/data-sync-ui/blob/master/ui/components/data-sources/BaseDataSourceDialog.js#L263

**Comment by wtrocki** [comment]
@pb82 I'm trying to prove that we could use mongo for both metadata and data so users could choose the right db at the start. This is not going to be merged soon - it's more investigation how to properly model interfaces for data so we will not be tied to single datasource. Got really nice results so we should be able to move forward with actual requirements.

**Comment by wtrocki** [comment]
Outdated.

**Pull request closed without merging**
